# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160317_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='auth_token',
            field=models.UUIDField(blank=True),
        ),
    ]
