# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-24 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160905_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='auth_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
