# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-02-12 06:08
from __future__ import unicode_literals

from django.db import migrations
import fossevents.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_moderator'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', fossevents.users.models.CustomUserManager()),
            ],
        ),
    ]
